from __future__ import annotations

import operator
import time
from collections import Counter
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Dict, List, Optional, Sequence, Tuple

from .analysis import find_unowned_paths, find_unused_entries, load_entries_and_repo_files
from .codeowners import (
    BlankLine,
    BlockItem,
    CheckDirective,
    CheckLineItem,
    CodeownersBlock,
    CodeownersEntry,
    CodeownersParseResult,
    CommentLine,
    GroupDefinition,
    StandaloneEntryItem,
)
from .git_activity import (
    build_activity_index,
    suggest_owners_for_paths,
    PathOwnershipSuggestion,
    CandidateSuggestion,
    GitActivityIndex,
)


@dataclass
class GuardrailStatus:
    directive: CheckDirective
    status: str
    member_count: Optional[int]
    passed: bool

    def to_dict(self) -> Dict[str, object]:
        return {
            "raw": self.directive.raw,
            "status": self.status,
            "member_count": self.member_count,
            "threshold": self.directive.threshold,
            "operator": self.directive.operator,
            "line_number": self.directive.line_number,
            "source": str(self.directive.source),
            "passed": self.passed,
        }


@dataclass
class MaskSuggestion:
    pattern: str
    base_path: str
    is_directory: bool
    depth: int
    unowned_count: int
    unowned_paths: List[str]
    total_commits: int
    candidates: List[CandidateSuggestion]

    def to_dict(self) -> Dict[str, object]:
        return {
            "pattern": self.pattern,
            "base_path": self.base_path,
            "is_directory": self.is_directory,
            "depth": self.depth,
            "unowned_count": self.unowned_count,
            "unowned_paths": list(self.unowned_paths),
            "total_commits": self.total_commits,
            "candidates": [
                {
                    "identity": candidate.identity,
                    "commits": candidate.commits,
                    "share": candidate.share,
                }
                for candidate in self.candidates
            ],
        }


@dataclass
class AuditResult:
    repo_root: Path
    codeowners_path: Path
    repo_url: Optional[str]
    branch: Optional[str]
    parse_result: CodeownersParseResult
    tracked_files_count: int
    unused_entries: List[CodeownersEntry]
    unowned_paths: List[str]
    top_directories: List[Tuple[str, int]]
    guardrails: List[GuardrailStatus]
    suggestions: List[PathOwnershipSuggestion]
    suggestion_targets: List[str]
    mask_suggestions: List[MaskSuggestion]
    config: Dict[str, object]
    duration_seconds: float

    @property
    def unused_total(self) -> int:
        return len(self.unused_entries)

    @property
    def unowned_total(self) -> int:
        return len(self.unowned_paths)

    @property
    def has_guardrail_failures(self) -> bool:
        return any(status.status != "pass" for status in self.guardrails)

    @property
    def has_issues(self) -> bool:
        return bool(self.unused_entries or self.unowned_paths or self.has_guardrail_failures)

    @property
    def used_entries(self) -> List[CodeownersEntry]:
        unused_ids = {id(entry) for entry in self.unused_entries}
        return [entry for entry in self.parse_result.entries if id(entry) not in unused_ids]

    def to_custom_codeowners(
        self,
        *,
        include_header: bool = True,
        include_group_definitions: bool = True,
        include_checks: bool = True,
    ) -> str:
        """Render the audit result into a CODEOWNERS file using the custom @@@ group notation."""

        lines: List[str] = []

        if include_header:
            lines.append("# Generated by codeowners_tools audit")
            lines.append("")

        layout = getattr(self.parse_result, "layout", None)

        def render_group_definition(definition: GroupDefinition) -> Optional[str]:
            members_blob = " ".join(definition.members)
            if definition.delimiter == ":":
                line = f"{definition.display_token}:{' ' + members_blob if members_blob else ''}"
            elif definition.delimiter == "=":
                if members_blob:
                    line = f"{definition.display_token} = {members_blob}"
                else:
                    line = f"{definition.display_token} ="
            else:
                line = f"{definition.display_token} {members_blob}".strip()
            if definition.comment:
                line = f"{line}{definition.comment}"
            return line.rstrip()

        def render_entry(entry: CodeownersEntry, indent: str = "") -> str:
            owners_tokens = entry.raw_owners or entry.owners
            body = entry.pattern
            if owners_tokens:
                body = f"{body} {' '.join(owners_tokens)}"
            line = f"{indent}{body}"
            if entry.inline_comment:
                line = f"{line}{entry.inline_comment}"
            return line.rstrip()

        def render_pattern(pattern: str, indent: str, inline_comment: Optional[str]) -> str:
            line = f"{indent}{pattern}"
            if inline_comment:
                line = f"{line}{inline_comment}"
            return line.rstrip()

        def render_check(check: CheckDirective, indent: str, inline_comment: Optional[str]) -> str:
            line = f"{indent}{check.raw}"
            if inline_comment:
                line = f"{line}{inline_comment}"
            return line.rstrip()

        def render_block(block: CodeownersBlock) -> List[str]:
            inner_lines: List[str] = ["{"]
            for item in block.items:
                if item.kind == "entry" and item.entry is not None:
                    indent = item.indent or item.entry.indent or "    "
                    inner_lines.append(render_entry(item.entry, indent))
                elif item.kind == "pattern" and item.pattern is not None:
                    indent = item.indent or "    "
                    inner_lines.append(render_pattern(item.pattern, indent, item.inline_comment))
                elif item.kind == "check" and include_checks and item.check is not None:
                    indent = item.indent or "    "
                    inner_lines.append(render_check(item.check, indent, item.inline_comment))
                elif item.kind == "comment" and item.text is not None:
                    indent = item.indent or ""
                    inner_lines.append(f"{indent}{item.text}".rstrip())
                elif item.kind == "blank":
                    inner_lines.append("")
                elif item.kind == "raw" and item.text:
                    indent = item.indent or ""
                    inner_lines.append(f"{indent}{item.text}".rstrip())
            inner_lines.append("}")
            return inner_lines

        if layout:
            for item in layout:
                if isinstance(item, BlankLine):
                    lines.append("")
                elif isinstance(item, CommentLine):
                    lines.append(f"{item.indent}{item.text}".rstrip())
                elif isinstance(item, GroupDefinition):
                    if include_group_definitions:
                        rendered = render_group_definition(item)
                        if rendered is not None:
                            lines.append(rendered)
                elif isinstance(item, StandaloneEntryItem) and item.entry is not None:
                    indent = item.indent or item.entry.indent or ""
                    lines.append(render_entry(item.entry, indent))
                elif isinstance(item, CheckLineItem) and item.check is not None:
                    if include_checks:
                        indent = item.indent or ""
                        lines.append(render_check(item.check, indent, item.inline_comment))
                elif isinstance(item, CodeownersBlock):
                    block_lines = render_block(item)
                    lines.extend(block_lines)
        else:
            if include_group_definitions and self.parse_result.groups:
                for group_name in sorted(self.parse_result.groups):
                    members = self.parse_result.groups[group_name]
                    member_blob = " ".join(members)
                    lines.append(f"@@@{group_name} {member_blob}".rstrip())
                lines.append("")

            for entry in self.parse_result.entries:
                lines.append(render_entry(entry))

            if include_checks and self.parse_result.checks:
                lines.append("")
                for check in self.parse_result.checks:
                    lines.append(check.raw)

        lines.append("")
        return "\n".join(lines)

    def to_dict(self) -> Dict[str, object]:
        return {
            "repo_root": str(self.repo_root),
            "codeowners_path": str(self.codeowners_path),
            "repo_url": self.repo_url,
            "branch": self.branch,
            "tracked_files_count": self.tracked_files_count,
            "config": self.config,
            "duration_seconds": self.duration_seconds,
            "unused_entries": [
                {
                    "pattern": entry.pattern,
                    "owners": entry.owners,
                    "line_number": entry.line_number,
                    "source": str(entry.source),
                }
                for entry in self.unused_entries
            ],
            "unowned_paths": self.unowned_paths,
            "top_directories": [
                {"path": path, "count": count} for path, count in self.top_directories
            ],
            "guardrails": [status.to_dict() for status in self.guardrails],
            "suggestions": [
                {
                    "path": suggestion.path,
                    "is_directory": suggestion.is_directory,
                    "total_commits": suggestion.total_commits,
                    "candidates": [
                        {
                            "identity": candidate.identity,
                            "commits": candidate.commits,
                            "share": candidate.share,
                        }
                        for candidate in suggestion.candidates
                    ],
                }
                for suggestion in self.suggestions
            ],
            "suggestion_targets": self.suggestion_targets,
            "mask_suggestions": [suggestion.to_dict() for suggestion in self.mask_suggestions],
            "used_entries": [
                {
                    "pattern": entry.pattern,
                    "owners": entry.owners,
                    "line_number": entry.line_number,
                    "source": str(entry.source),
                }
                for entry in self.used_entries
            ],
            "groups": self.parse_result.groups,
        }


_COMPARE = {
    ">": operator.gt,
    ">=": operator.ge,
    "<": operator.lt,
    "<=": operator.le,
    "==": operator.eq,
    "!=": operator.ne,
}


def evaluate_guardrails(
    checks: Sequence[CheckDirective],
    groups: Dict[str, Sequence[str]],
) -> List[GuardrailStatus]:
    results: List[GuardrailStatus] = []
    for check in checks:
        if not check.group:
            results.append(GuardrailStatus(check, "unparsed", None, False))
            continue
        members = groups.get(check.group)
        if members is None:
            results.append(GuardrailStatus(check, "missing-group", None, False))
            continue
        comparator = _COMPARE.get(check.operator)
        if comparator is None:
            member_list = list(members)
            results.append(GuardrailStatus(check, "unsupported-operator", len(member_list), False))
            continue
        member_list = list(members)
        size = len(member_list)
        passed = comparator(size, check.threshold)
        status = "pass" if passed else "fail"
        results.append(GuardrailStatus(check, status, size, passed))
    return results


def _determine_suggestion_targets(
    unowned_paths: List[str],
    display_limit: int,
    explicit_targets: Optional[Sequence[str]] = None,
) -> List[str]:
    if explicit_targets:
        return list(explicit_targets)
    if not unowned_paths:
        return []
    if display_limit <= 0:
        return []
    slice_limit = min(display_limit, len(unowned_paths))
    sample = unowned_paths[:slice_limit]
    if sample:
        return sample
    return []


@dataclass
class _MaskPatternAccumulator:
    base_path: str
    is_directory: bool
    depth: int
    paths: set[str]


def _normalize_repo_path(path: str) -> str:
    return PurePosixPath(path).as_posix().strip("/")


def _mask_pattern_candidates(
    path: str,
    mode: str,
    depth_limit: int,
) -> List[Tuple[str, str, int, bool]]:
    normalized = _normalize_repo_path(path)
    if not normalized:
        return []

    segments = [segment for segment in normalized.split("/") if segment]
    if not segments:
        return []

    file_name = segments[-1]
    dir_segments = segments[:-1]
    results: List[Tuple[str, str, int, bool]] = []

    if dir_segments:
        max_depth = len(dir_segments) if depth_limit <= 0 else min(depth_limit, len(dir_segments))
        for depth in range(1, max_depth + 1):
            prefix_segments = dir_segments[:depth]
            base_path = "/".join(prefix_segments)
            if mode == "file":
                extension = ""
                if "." in file_name:
                    extension = file_name[file_name.rfind(".") :]
                if extension:
                    pattern = f"/{base_path}/*{extension}" if base_path else f"/*{extension}"
                else:
                    pattern = f"/{base_path}/*" if base_path else "/*"
            else:  # directory
                pattern = f"/{base_path}/*" if base_path else "/*"
            results.append((pattern, base_path, depth, True))

    if mode == "file":
        base_path = "/".join(segments)
        pattern = f"/{base_path}" if base_path else "/"
        results.append((pattern, base_path, len(segments), False))

    return results


def _collect_mask_patterns(
    unowned_paths: Sequence[str],
    mode: str,
    depth_limit: int,
) -> Dict[str, _MaskPatternAccumulator]:
    accumulator: Dict[str, _MaskPatternAccumulator] = {}
    for path in unowned_paths:
        candidates = _mask_pattern_candidates(path, mode, depth_limit)
        for pattern, base_path, depth, is_directory in candidates:
            entry = accumulator.get(pattern)
            if entry is None:
                entry = _MaskPatternAccumulator(
                    base_path=base_path,
                    is_directory=is_directory,
                    depth=depth,
                    paths=set(),
                )
                accumulator[pattern] = entry
            else:
                entry.depth = min(entry.depth, depth)
            entry.paths.add(_normalize_repo_path(path))
    return accumulator


def _build_mask_suggestions(
    index: Optional[GitActivityIndex],
    pattern_accumulator: Dict[str, _MaskPatternAccumulator],
    limit: int,
    min_commits: int,
) -> List[MaskSuggestion]:
    if not pattern_accumulator:
        return []
    if index is None:
        return []

    suggestions: List[MaskSuggestion] = []
    for pattern, data in pattern_accumulator.items():
        base_path = data.base_path
        if data.is_directory:
            target = f"{base_path}/" if base_path else "/"
        else:
            target = base_path
        suggestion = suggest_owners_for_paths(
            index,
            [target],
            limit=limit,
            min_commits=min_commits,
        )[0]
        suggestions.append(
            MaskSuggestion(
                pattern=pattern,
                base_path=base_path,
                is_directory=data.is_directory,
                depth=data.depth,
                unowned_count=len(data.paths),
                unowned_paths=sorted(data.paths),
                total_commits=suggestion.total_commits,
                candidates=list(suggestion.candidates),
            )
        )

    suggestions.sort(key=lambda item: (-item.unowned_count, item.pattern))
    return suggestions


def generate_audit(
    repo_root: Path,
    codeowners_path: Path,
    *,
    repo_url: Optional[str] = None,
    branch: Optional[str] = None,
    max_unowned: int = 20,
    suggest_limit: int = 3,
    min_commits: int = 1,
    mask_mode: str = "directory",
    mask_depth: int = 3,
    include_merges: bool = False,
    since: Optional[str] = None,
    restrict_to_targets: bool = False,
    explicit_targets: Optional[Sequence[str]] = None,
    top_directory_limit: int = 10,
) -> AuditResult:
    start = time.perf_counter()

    parse_result, tracked_files = load_entries_and_repo_files(
        codeowners_path,
        repo_root,
    )

    unused_entries = find_unused_entries(parse_result.entries, tracked_files)
    unowned_paths = find_unowned_paths(parse_result.entries, tracked_files)

    top_counter: Counter[str] = Counter(path.split("/", 1)[0] for path in unowned_paths)
    top_directories = top_counter.most_common(top_directory_limit)

    guardrails = evaluate_guardrails(parse_result.checks, parse_result.groups)

    normalized_mask_mode = mask_mode if mask_mode in {"directory", "file"} else "directory"
    depth_limit = max(mask_depth, 0)

    mask_patterns = _collect_mask_patterns(unowned_paths, normalized_mask_mode, depth_limit)

    suggestion_targets = _determine_suggestion_targets(
        unowned_paths,
        max_unowned,
        explicit_targets=explicit_targets,
    )

    suggestions: List[PathOwnershipSuggestion] = []
    mask_suggestions: List[MaskSuggestion] = []

    needs_activity_index = bool(suggestion_targets) or bool(mask_patterns)
    index: Optional[GitActivityIndex] = None

    if needs_activity_index:
        if restrict_to_targets:
            if suggestion_targets:
                paths_for_log: Optional[Sequence[str]] = suggestion_targets
            elif unowned_paths:
                paths_for_log = unowned_paths
            else:
                paths_for_log = None
        else:
            paths_for_log = None

        index = build_activity_index(
            repo_root=repo_root,
            include_merges=include_merges,
            since=since,
            paths=paths_for_log,
        )

    if suggestion_targets and index is not None:
        suggestions = suggest_owners_for_paths(
            index,
            suggestion_targets,
            limit=suggest_limit,
            min_commits=min_commits,
        )

    if mask_patterns and index is not None:
        mask_suggestions = _build_mask_suggestions(
            index,
            mask_patterns,
            limit=suggest_limit,
            min_commits=min_commits,
        )

    duration = time.perf_counter() - start

    return AuditResult(
        repo_root=repo_root,
        codeowners_path=codeowners_path,
        repo_url=repo_url,
        branch=branch,
        parse_result=parse_result,
        tracked_files_count=len(tracked_files),
        unused_entries=unused_entries,
        unowned_paths=unowned_paths,
        top_directories=top_directories,
        guardrails=guardrails,
        suggestions=suggestions,
        suggestion_targets=suggestion_targets,
        mask_suggestions=mask_suggestions,
        config={
            "max_unowned": max_unowned,
            "suggest_limit": suggest_limit,
            "min_commits": min_commits,
            "mask_mode": normalized_mask_mode,
            "mask_depth": depth_limit,
            "include_merges": include_merges,
            "since": since,
            "restrict_to_targets": restrict_to_targets,
            "explicit_targets": list(explicit_targets) if explicit_targets else None,
            "top_directory_limit": top_directory_limit,
        },
        duration_seconds=duration,
    )